<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>PesaGraph.Shared</RootNamespace>
    <AssemblyName>PesaGraph.Shared</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Mapster" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.11" />
  </ItemGroup>
</Project>
